### ISSUE TITLE
Elegir motor para SQL

### ISSUE THREAD

**Issue by BigAndres1209a** [ISCOUTB/AH-PETSADDOPT#5]

**Comment by serna0120** [comment]
Elegimos PostgreSQL como motor para el SQL.[ELECCION DE MOTOR PARA BASE SQL POSTGRESQL.pdf](https://github.com/user-attachments/files/16956960/ELECCION.DE.MOTOR.PARA.BASE.SQL.POSTGRESQL.pdf)

**Comment by jairoserrano** [comment]
adelante
